# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
Import('cppEnv')


env = cliEnv.Clone()

env.UseLibrary(['cmocka'])



env.AddCflags([
    '-DHAVE_SIGNAL_H'
])


cppEnv.Program('test-cpp', [
    'test-cpp.cpp',
])
