LIBIARY_DIR = "$BASE_DIR/ulibs"
LVGL_DIR = "$BASE_DIR/thrid_party/lvgl"

config("compile_flags") {
  defines = [
    "LV_CONF_INCLUDE_SIMPLE",
  ]
  cflags = [
    "-mcpu=cortex-a72+nofp",
    "-g",
  ]
  cflags_c = [
    "-nostdlib",
    "-nostdinc",
    "--no-standard-libraries"
  ]
  ldflags = [
    "-nostdlib",
    "-v"
  ]
}

executable("Settings") {
  configs += [
    ":compile_flags",
  ]
  deps = [
    "//ulibs/libsystem:statemgr_client",
    "//ulibs:uapp_gui_runtime",
  ]
  include_dirs = [
    "$BASE_DIR/thrid_party",
    "$LIBIARY_DIR/liblvgl/compat",
    "$LIBIARY_DIR/include",
    "$LIBIARY_DIR/liblvgl",
    "$LVGL_DIR",
    "$LVGL_DIR/src",
    "include",
  ]
  ldflags += [
    "-T",
    "$LIBIARY_DIR/libcrt/uapp.lds"
  ]
  sources = [
    "$LIBIARY_DIR/libcrt/start.S",
    "main.c",
  ]
}
