# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cppCliEnv')

env=cppCliEnv.Clone()
# cppEnv.UseLibc()


cflags='  -DLIBYC -DIS_LITTLE_ENDIAN  -DIS_LINUX  -D_REENTRANT  -DHAVE_STD_STRING_VIEW -fpermissive -DRUN_ENVIRONMENT_LINUX -DCHINESE_SUPPORT -DMOUSE_SUPPORT -DRESMGT_SUPPORT -DMODE_DEBUG ' #RUN_ENVIRONMENT_WIN32 RUN_ENVIRONMENT_LINUX 



include = [
    '#eggs/libsdl2',
    '#eggs/libsdl2-ttf',
    '#eggs/libsdl2/include',
    '#eggs/libjpeg/',
    '#eggs/libfreetype/include',
    '#eggs/include/SDL2/',
    '.',
    '#eggs/libsdl2/include',
]
env.UseLibApp()
env.UseLibrary(['sdl2'])
env.AddCxxFlags(cflags)
env.AddInclude(include)


env.Program('monogui', [
    Glob('tgui/*.cpp'),
    Glob('demo/*.cpp')
])