# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')
Import('cppEnv')


env = env.Clone(
    w=GetOption('w'),
    ENV=os.environ,
    PATH=[os.environ['PATH'], '/opt/local/bin'],
)

source = [
    'test.c',
]

libs = [
    'libcmocka.a',
    'libpng.a',
    'libzlib.a',
]+env['LIBC'] 

source = [
    'pngtest.c',
]

env.Program('pngtest', source,
            LIBS=libs+env.get('LIBS')
            )

