# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env = appEnv

env.UseLibrary([
    'libsdl2-ttf.a',
    'libfreetype.a',
    'libsdl2.a',
    'libgui.a',
    'libsdl2-image.a',
    'libimage.a',
    'libwebp.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
])

env.Program('pngtest', [
    'pngtest.c',
])
