# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env=appEnv

source = [
    'main.c'
]


libs = [
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a']

env.Program('gui', source,
            LIBS=libs+env.get('LIBS'),
            CFLAGS='$CFLAGS $LIBCFLAGS',
            )

# env.Objcopy('gui','gui',OBJCOPYFLAGS='-S --strip-all')
# env.Objcopy('gui.dbg','gui',OBJCOPYFLAGS='--only-keep-debug')
