# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source = []
source += Glob('src/*.c')
source += Glob('sys/sdl2/*.c')
source += Glob('lib/gz/*.c')
source += Glob('lib/xz/*.c')
source += Glob('sys/yiyiya/*.c')

source += [


]
libs = [
    'libsdl2.a',
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]+env['LIBC']

include = [
    '../../eggs/libgui',
    '../../eggs/libsdl2',
    '../../eggs/libsdl2/include',
    '../../eggs/libjpeg/',
    '../../eggs/libfreetype/include',
    'sys/sdl2/',
    'include',
    '.',
    '../../eggs/include',
]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype',
    '../../eggs/libwebp/',
    '../../eggs/libgui',
    '../../eggs/libimage',
    '../../eggs/libjpeg',
    '../../eggs/libpng',
    '../../eggs/libc/',
    '../../eggs/libzlib',

]

env.Program('gnuboy', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=libpath+env['LIBPATH'],
            CPPPATH=include+env['CPPPATH'],
            )
