# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')
Import('cppEnv')

env = cppEnv.Clone()

cflags = ' -DIS_LITTLE_ENDIAN  -DIS_LINUX  -D_REENTRANT  -DHAVE_STD_STRING_VIEW '

# cflags+='-DSDL_IMAGE_USE_COMMON_BACKEND \
# 		-DLOAD_BMP -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
# 		-DLOAD_SVG -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_XV \
# 		 -DLOAD_PNG -DLOAD_WEBP\
#         -DLOAD_JPG  -DFAST_IS_JPEG\
#         '

libs = [
    'libsdl.a',
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
    'libsdl-ttf.a',
    'libsdl-image.a',
    'libfreetype.a',
    'libsdl.a',
    'libwebp.a',
    'libjpeg.a',
]

include = [
    '#eggs/libcxx/include',
    '#eggs/libcxxabi/include',

    '#eggs/libgui',
    '#eggs/libsdl-ttf',
    '#eggs/libsdl-image',
    '#eggs/libjpeg/',
    '#eggs/libfreetype/include',
    'include',
    '.',
    '#eggs/include',
    '#eggs/include/SDL',

]

libpath = [
    '#eggs/libcxx/',
    '#eggs/libcxxabi/',
    '#eggs/libsdl/',
    '#eggs/libsdl-image/',
    '#eggs/libsdl-ttf/',
    '#eggs/libfreetype',
    '#eggs/libwebp/',
    '#eggs/libgui',
    '#eggs/libimage',
    '#eggs/libjpeg',
    '#eggs/libpng',
    '#eggs/libc/',
    '#eggs/libzlib',

]

env.UseLibApp()
env.AddInclude(include)
env.AddPath(include)

env.UseLibrary([
    'libsdl-ttf.a',
    'libfreetype.a',
    'libsdl.a',
    'libgui.a',
    'libsdl-image.a',
    'libimage.a',
    'libwebp.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
])

env.Program('testwm',
            ['testwm.c'])


env.Program('testoverlay',
            ['testoverlay.c'])


env.Program('testoverlay2',
            ['testoverlay2.c'])


env.Program('testbitmap',
            ['testbitmap.c'])
