# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env=appEnv


source=[ 
]

source+= Glob('*.c')

libs=[
    'liblvgl-8.0.0.a',
    'libgui.a',
    'libimage.a',
    'libpng.a',
]

libpath=[
    '#/eggs/liblvqrcode',
    '#eggs/liblvgl-8.0.0'
]
include=[
    '#/eggs/liblvgl-8.0.0',
    '#/eggs/liblvqrcode',
    '.',
    'xtrack/Pages',
    'xtrack/Pages/Config',
    'xtrack/Pages/Resource',
    'xtrack/'
]


cflags='  -DLV_LVGL_H_INCLUDE_SIMPLE=1 '

env.Program('track', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS ='$CFLAGS '+cflags,
    )

