# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env=appEnv

libs=[
    'libetk.a',
    'libjpeg.a',
    'libgui.a',
]+env['LIBC']

source=[
    'main.c',
    'etk_app.c',
    'sinclock.c',
    'mine.c',
    'terminal.c',
    # 'light.c',
    'power.c',
    'temhum.c',
    'status.c',
    ]

env.Program('etk', source,
    LIBS=libs+env.get('LIBS'))

# env.Objcopy('etk','etk',OBJCOPYFLAGS='-S')
# env.Objcopy('etk.dbg','etk',OBJCOPYFLAGS='--only-keep-debug')


