# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')



source= [
    'main.c',
]

source+= Glob('lib/*.c')


# source+= Glob('toys/posix/*.c')
# source+= Glob('toys/example/*.c')
# source+= Glob('toys/lsb/*.c')
# source+= Glob('toys/net/*.c')
# source+= Glob('toys/other/*.c')
# source+= Glob('toys/pending/*.c')

source+= [
    'toys/example/hello.c',
    'toys/posix/ls.c',
]

source+=[ 
    ]
    




env.Program('toybox', source,
    CFLAGS='$CFLAGS  $LIBCFLAGS  -Iapp/toybox -D__linux__ -DCFG_TOYBOX',
    LINKFLAGS= '$LINKFLAGS')
