# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
env=cliEnv


source = [
    'ls.c',
]

ls=env.Program('ls', source)

source = [
    'echo.c',
]

echo=env.Program('echo', source)


source = [
    'cat.c',
]


cat=env.Program('cat', source)

source = [
    'hexdump.c',
]


hexdump=env.Program('hexdump', source)


source = [
    'touch.c',
]


touch=env.Program('touch', source)


source = [
    'date.c',
]

date=env.Program('date', source)


source = [
    'kill.c',
]

kill=env.Program('kill', source)

returns=[ls]

Return('returns')
