# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
env = cliEnv

ls = env.Program('ls', [
    'ls.c',
])


echo = env.Program('echo', [
    'echo.c',
])


cat = env.Program('cat', [
    'cat.c',
])

hexdump = env.Program('hexdump', [
    'hexdump.c',
])


touch = env.Program('touch', [
    'touch.c',
])

date = env.Program('date', [
    'date.c',
])


kill = env.Program('kill', [
    'kill.c',
])

shell = env.Program('shell', [
    'shell.c',
])

returns = [ls, echo, date, kill, touch, hexdump, cat]

Return('returns')
