# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
    w=GetOption('w'),
    ENV=os.environ,
    PATH=[os.environ['PATH'], '/opt/local/bin'],
)

source = [
    'ls.c',
]

env.Program('ls', source,)


source = [
    'echo.c',
]

env.Program('echo', source)


source = [
    'cat.c',
]


env.Program('cat', source)


source = [
    'hexdump.c',
]


env.Program('hexdump', source)


source = [
    'touch.c',
]


env.Program('touch', source)


source = [
    'date.c',
]

env.Program('date', source)
