# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

libs=[
    'liblvgl.a',
    'libgui.a',
    'libimage.a',
    'libpng.a',
]

source= []
    
source += Glob('*.c')
source += Glob('page/*.c')

env.Program('watch', source,
    LIBS=libs+env.get('LIBS'),
    CFLAGS='$CFLAGS $LIBCFLAGS -DLV_LVGL_H_INCLUDE_SIMPLE=1 -Iapp/watch/page ',
)