# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env=appEnv

libs=[
    'liblvgl.a',
    'libgui.a',
    'libimage.a',
    'libpng.a',
]

libpath=[
    '#/eggs/liblvqrcode',
    '#eggs/liblvgl'
]

include=[
    '#/eggs/liblvgl',
    '#/eggs/liblvqrcode',
    '.',
]

source= []
    
source += Glob('*.c')
source += Glob('page/*.c')

env.Program('watch', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS -DLV_LVGL_H_INCLUDE_SIMPLE=1 -Iapp/watch/page ',
)