# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
env=cliEnv


source = [
    'main.c',
]

libs = [
    'libchez.a',
    'libzlib.a',
    'liblz4.a',
    'libuuid.a',
]

libpath = [
    '../../eggs/libchez/',
    '../../eggs/libzlib/',
    '../../eggs/liblz4/',
    '../../eggs/libuuid',
]



type = 'a6le'
cflags = ''

if env['ARCHTYPE'] == 'arm':
    type = 'arm32le'
    cflags = '-DINLINES -DGC_MACROS -DARMV6 -DMB_LEN_MAX=8 -D_LARGEFILE64_SOURCE -DHAVE_HIDDEN'
elif env['ARCHTYPE'] == 'x86':
    type = 'i3le'
    cflags = '-DI386 -DINLINES -DGC_MACROS  -DMB_LEN_MAX=8 -D_LARGEFILE64_SOURCE -DHAVE_HIDDEN'
else:
    print('scheme not support ', env['ARCHTYPE'])


include = [
    'src',
    'include',
    '.',
    '../../eggs/libchez/'+type
]


env.Program('scheme', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS'+cflags,
            )
