# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('appEnv')
env = appEnv

source= [
    'main.c',
    'microui.c',
    'renderer.c',
    ]


env.Program('microui',source)

# env.Objcopy('microui','microui',OBJCOPYFLAGS='-S')
# env.Objcopy('microui.dbg','microui',OBJCOPYFLAGS='--only-keep-debug')


