# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')
Import('cppCliEnv')

cppEnv = cppCliEnv.Clone()

# -DIS_LITTLE_ENDIAN
cflags = ' -DIS_LINUX  -D_REENTRANT  -DHAVE_STD_STRING_VIEW -DLOG_LEVEL=4 '

# cflags+='-DSDL_IMAGE_USE_COMMON_BACKEND \
# 		-DLOAD_BMP -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
# 		-DLOAD_SVG -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_XV \
# 		 -DLOAD_PNG -DLOAD_WEBP\
#         -DLOAD_JPG  -DFAST_IS_JPEG\
#         '

cflags += ' -DENABLE_CLOCK '


include = [
    '../../eggs/libgui',
    '../../eggs/libsdl-ttf',
    '../../eggs/libsdl-image',
    '../../eggs/libjpeg/',
    '../../eggs/libfreetype/include',
    'include',
    '.',
    '../../eggs/include',
    '../../eggs/include/SDL',

]


cppEnv.UseLibrary([
    # 'libsdl.a',

    'libsdl-ttf.a',
    'libfreetype.a',
    'libsdl.a',
    'libgui.a',
    'libsdl-image.a',
    'libimage.a',
    'libwebp.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
])

cppEnv.UseLibApp()

cppEnv.AddCxxFlags(cflags)
cppEnv.AddInclude(include)

cppEnv.Program('gmenu', [
    Glob('src/*.cpp')
])
